### PR TITLE
Fix Light Accessory Saturation Issue on Raspberry Pi & minor Improvements

### PR DESCRIPTION
**Pull request by resonaura**
@kakopappa 

This Pull Request resolves a critical issue where the **Saturation** characteristic was not correctly applied on Raspberry Pi, while **Hue** was functioning as expected.

## 🔧 Changes Introduced:
- **Fixed Saturation Handling on Raspberry Pi**  
  - Addressed a bug that caused the **Saturation** value not to apply correctly in certain environments (e.g., Raspberry Pi).  
- **Improved Consistency of Color Controls**  
  - Ensured smooth and reliable application of **Hue**, **Saturation**, and **Color Temperature** settings.

## 📦 Version Update:
- **Updated version to 1.1.4**  
  - The package version has been incremented to **1.1.4** to reflect the bug fixes and improvements.  
  - **⚠️ Note:** **It is important to publish this version after merge to **npm** to make the fix available to users.**

## 📝 Notes:
- Please review the changes and let me know if further adjustments are needed.  
- Feedback is welcome to ensure everything is functioning as intended.  

Thank you again for your time and support!

### CODE REVIEW

**Comment by kakopappa** [comment]
Thanks @resonaura 

May I know why we need a delay to apply?

**Comment by resonaura** [comment]
Hi @kakopappa,

The main reason for adding the delay is that, unfortunately, the request gets sent to the device twice – once for Hue and once for Saturation. Sometimes, these updates apply in different orders (e.g., Saturation first and then Hue, or vice versa), which can result in the final color not matching the expected outcome.

Additionally, HomeKit only allows these characteristics (Hue and Saturation) to be handled separately, rather than through a single unified characteristic. This limitation makes it necessary to introduce a debounce mechanism. The short delay ensures that both values are processed together and the correct color is applied.

This solution improves the consistency of color updates and avoids unexpected results caused by the order of operations.

Let me know if anything needs further clarification!

**Comment by resonaura** [comment]
If everything looks good to you, I would really appreciate it if you could publish a new version to npm

**Comment by kakopappa** [comment]
Done

**Comment by resonaura** [comment]
Btw, @kakopappa, I also noticed that in **Google Home**, the temperature and humidity sensor is being displayed as a thermostat. Is it possible to display it simply as a sensor instead?

If that's not possible, is there at least a way to prevent it from showing that the thermostat is actively cooling the room? It would also be great if it could display the current temperature directly instead of just showing "1".

I’ll attach a screenshot for reference.

image

**Comment by resonaura** [comment]
Thank you for updating new version to npm!

**Comment by kakopappa** [comment]
Hi @resonaura 

The last time I checked, the Google Home app did not have proper Temperature Sensor support (it used to show as a sensor without showing any values). Thus, decided to use the Thermostat so at least we can see the temperature.

Will take a look at the current status. 

Thanks a lot for your contribution to the project

**Comment by kakopappa** [comment]
Hi @resonaura 

Just did a test. It looks like Google Home app supports now. 

image


I will include this in the next release which scheduled to happen in next 1-2 days

**Comment by resonaura** [comment]
Hi @kakopappa,

Thank you as well for making the integration of iOS devices into Google and Apple Home easier. ☺️

It's great that you'll include this in the next update — looking forward to it!

**Pull request merged**
